# this file should be stored at /etc/X11/xorg.conf.d/90-touchpad.conf

Section "InputClass"
  Identifier "touchpad"
  MatchIsTouchpad "on"
  Driver "Libinput"
  Option "Tapping" "on"
  Option "NaturalSCrolling" "on"
  Option "ScrollMethod" "twofinger"
EndSection
