# read $HOME/a/notes/tmux/tmux.org
#
# to run .tmux.conf again from a running server using the command prompt:
# :source ~/.tmux.conf

# note: # set-option (alias: set) # -g: sets global session or window options
# unbind all the keys
#unbind-key -a

# change the prefix key
#unbind C-b
#set-option -g prefix C-Space
#bind C-Space send-prefix

# enable mouse control (clickable windows, panes, resizable panes)
#set-option -g mouse on

# selects keybinds to be used in copy mode
#set-option -g mode-keys emacs
set-option -g mode-keys vi
# selects keybinds to be used at the command prompt
#set-option -g status-keys emacs
set-option -g status-keys vi

# windows indexes start from 1 instead of 0
set-option -g base-index 1
set-option -g pane-base-index 1

# time in milliseconds the pane numbers are shown for prefix q
set-option -g display-panes-time 5000
# time in milliseconds for which messages on the status line are shown 
set-option -g display-time 5000



#set -g status-bg purple
#set -g window-status-style bg=cyan,fg=black
#set -g window-status-current-style bg=green,fg=black


################################################################################


# note: if -T is not given, the key is put in the prefix table
# note: -n is a shorthand for -Troot

# add a bind (prefix-v) to enter in copy mode
bind-key -T prefix v copy-mode
# add binds to copy-mode-vi mode
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X begin-selection

# escape key to leave copy mode (also works for ^[)
bind-key -T copy-mode-vi Escape send-keys -X cancel
# I didn't notice a difference
set -g escape-time 1

# to enable copy to CLIPBOARD (and to PRIMARY) on terminals that don't support OSC 52 escape sequences
# note: alacritty (kitty) and other modern terminals don't need these lines; unfortunetely, this is not the case for xterm
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xsel -i -b; xsel -i -p"
#bind-key -Tcopy-mode-vi y send-keys -X copy-pipe-and-cancel "xsel -i -b"

# add hjkl movement binds
bind-key -T prefix h select-pane -L
bind-key -T prefix j select-pane -D
bind-key -T prefix k select-pane -U
bind-key -T prefix l select-pane -R

# add hjkl resize binds
bind-key -r -T prefix H resize-pane -L
bind-key -r -T prefix J resize-pane -D
bind-key -r -T prefix K resize-pane -U
bind-key -r -T prefix L resize-pane -R
# note: -r enables repeat

########################################

bind-key -n M-C-s set-option status off
# or just ^b: 'set status off'

